// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvthbfkfonzcxzwaurqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dGhiZmtmb256Y3h6d2F1cnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDIxMTEsImV4cCI6MjA1OTkxODExMX0.n2ty1n7_kpNnmuglyhTW1F280STSxRUh1qFVNKcd_Ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);